### PR TITLE
CI-Testing on Travis

### PR DESCRIPTION
**Pull request by guicho271828**
This is an inital attempt to make this library look more normal as a common lisp library.
I did not make actual changes yet; follow the further updates.

Tasks:

+ [x] follow the standard directory structure (src/ and t/)
+ [x] follow the standard package structure
+ [x] follow the standard convention for loading the asdf system (example codes below examples/)
+ [x] make hdf5-cffi-configure more reliable. make it "just work" on a vanilla ubuntu rig.
+ [ ] (optional) replace all examples with [roswell](https://github.com/roswell/roswell) scripts.

### CODE REVIEW

**Comment by guicho271828** [comment]
A few tests fails, but it loads fine on my system. Specifically,

```
 --------------------------------
 GROUPS []: 
      While running test examples/groups/h5ex-g-iterate.lisp:
  Invalid handle found..
 --------------------------------
 --------------------------------
 GROUPS []: 
      While running test examples/groups/h5ex-g-traverse.lisp:
  Invalid handle found..
 --------------------------------
 --------------------------------
 GROUPS []: 
      While running test examples/groups/h5ex-g-visit.lisp:
  Component HDF5-EXAMPLES not found.
 --------------------------------
 --------------------------------
 BASICS []: 
      While running test examples/basics/h5-cmprss.lisp:
  Invalid handle found..
 --------------------------------
```

**Comment by guicho271828** [comment]
On Travis, pkg-config is currently failing to find the appropriate header (I ditched the old custom header search mechanism), so Im working on it.

**Comment by guicho271828** [comment]
Now the build on travis passes on sbcl.
https://travis-ci.org/guicho271828/hdf5-cffi

**Comment by gheber** [comment]
Thanks a ton @guicho271828 . Give me a few days to get my head around this.

**Comment by guicho271828** [comment]
cleaned the commit logs further.

**Comment by guicho271828** [comment]
I think previously the h5cc did some magic to avoid the problems regarding H5OPEN and H5CHECK macros. This has prevented the standard build process using cffi-grovel. I changed the code so that it does not assume h5cc, but it means that the groveller completely skips calling H5OPEN. This is a problem, since H5OPEN initializes some internal variables, and without that, some examples do not work. I just added a call to `h5open` in the load time, ensuring that the library is fully initialized.

Also, some files mentioned in the examples are assuming the pathnames of the result h5 files, so I fixed it.

**Comment by guicho271828** [comment]
Fixed the travis builds because SZIP was not installed

**Comment by guicho271828** [comment]
I think now you can fully merge this commit without any degradation.

**Comment by guicho271828** [comment]
ping

**Comment by guicho271828** [comment]
thanks. now the next step should be submitting the library to quicklisp.

**Comment by gheber** [comment]
Agreed. Thanks a ton for your help.

**Pull request merged**
